# Generated by Django 5.2.1 on 2026-04-19 19:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='otp',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_otp',
            field=models.CharField(default=core.models.generate_otp, max_length=6),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_otp',
            field=models.CharField(default=core.models.generate_otp, max_length=6),
        ),
    ]
