# Generated by Django 5.2.1 on 2026-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_delivery_options_remove_delivery_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
